title: Datenstrukturen und KI
author: Michael Brenner
copyright: "2025"
# logo: figures/TUDelft_logo_rgb.png #add your own logo here

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  favicon : "figures/favicon.ico"
  baseurl :  "https://github.io/jil91/ds_ki-js2" #Replace this with your own URL
  home_page_in_navbar       : true
  extra_footer: |
        <div>
            🤖
        </div>
  # Hier können andere html-bezogene Einstellungen stehen, z.B.
  # use_repository_button: true
  # home_page_in_navbar: false
  # baseurl: "https://jil91.github.io/ds_ki-js2/" # Nur wenn du eine Basis-URL hast

  html_extra_path: ["_static/pdfs"] # <-- Diese Zeile ist entscheidend!

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - attrs_block # https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#block-attributes
    - attrs_inline # https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#syntax-attributes-inline
    - colon_fence
    - deflist # https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#syntax-definition-lists
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
  myst_url_schemes: [ mailto, http, https ]
  myst_dmath_double_inline: true



#######################################################################################
# Advanced and power-user settings
sphinx:
  config:
    language: de
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      # home_page_in_toc: true
      repository_url: "https://github.com/jil91/ds_ki-js2" #add your own repo URL here
      use_repository_button: true
      use_issues_button : false
      launch_buttons:
        thebe: true
    html_show_copyright: true  # Evtl ändern?
    tippy_add_class: "has-tippy"
  extra_extensions:
    - sphinx.ext.imgconverter
    #- jupyterbook_patches
    - teachbooks_sphinx_tippy # https://github.com/TeachBooks/teachbooks-sphinx-tippy

bibtex_bibfiles: 
  - references.bib
