name: Deploy Book

on:
  push:
    branches:
      - main
    paths:
      - book/**
      - .github/workflows/call-deploy-book.yml
  workflow_dispatch: # Ermöglicht manuelles Auslösen in GitHub Actions

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Wichtig für gh-pages Action

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Oder die Version, die du lokal verwendest

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jupyter-book==1.0.4 # Oder deine genaue Version
          pip install myst-parser # Falls du myst-nb verwendest, installiere dies auch
          # Optional: pip install myst-nb # Falls du Jupyter Notebooks hast

      - name: Build the Book
        run: |
          cd book # Wechsel in den 'book'-Ordner, wo dein _config.yml ist
          jupyter-book build .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_build/html # Hier sind die fertigen HTML-Dateien nach dem Build
          publish_branch: gh-pages # Hierher wird der Branch erstellt/aktualisiert